### create user
POST https://user-management-backend-xn7y.onrender.com/user-api/users
Content-Type: application/json

{
  "name": "Pavan",
  "email": "pavan@gmail.com",
  "dateOfBirth": "2006-02-15",
  "mobileNumber": 1234567890
}

### read all users
GET https://user-management-backend-xn7y.onrender.com/user-api/users

### read a user by id
GET https://user-management-backend-xn7y.onrender.com/user-api/users/69a691476d783cbefc632416

### delete a user
DELETE  https://user-management-backend-xn7y.onrender.com/user-api/users/69a691476d783cbefc632416

### Activate user
PATCH   https://user-management-backend-xn7y.onrender.com/user-api/users/69a691476d783cbefc632416